before_build:
 - nuget restore src/C#/RobotArmController.sln
 - choco install opencover.portable
 - choco install codecov
build_script:
 -  dotnet build src/C#/RobotArmController.sln
test_script:
 - dotnet test --no-build src/C#/Tests/Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
 - codecov -f "coverage.xml"

