before_build:
 - nuget restore src/C#/RobotArmController.sln
 - choco install opencover.portable
 - choco install codecov
build_script:
 -  dotnet build src/C#/RobotArmController.sln
test_script:
 - OpenCover.Console.exe -register:user -target:"xunit.console.x86.exe" -targetargs:".\src\C#\Tests\bin\Debug\netcoreapp2.1\Tests.dll -noshadow -appveyor"  -output:"coverage.xml"
 - codecov -f "coverage.xml"

