before_build:
 - nuget restore src/C#/RobotArmController.sln
 - choco install opencover.portable
 - choco install codecov
build_script:
 -  dotnet build src/C#/RobotArmController.sln
test_script:
 - OpenCover.Console.Exe -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test ./src/C#/Tests/Tests.csproj" -oldstyle -register:user -output:"coverage.xml"
 - codecov -f "coverage.xml"

